trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    includePreviewVersions: true

- task: PowerShellInstaller@1
  displayName: 'Install PowerShell Core'
  inputs:
    version: '7.1.3'

- task: PowerShell@2
  displayName: 'Run PowerShell script'
  inputs:
    targetType: 'filePath'
    filePath: 'path/to/script.ps1'
    errorActionPreference: 'stop'
